const slider = document.querySelector(".slider");
const main = document.querySelector("main");
const socialH = document.querySelector("h1");
const todayH = document.querySelector(".todayH2");
const todayNumber = document.querySelector(".today-number");
const fbTop = document.querySelector(".fb");
const twTop = document.querySelector(".tw");
const igTop = document.querySelector(".ig");
const ytTop = document.querySelector(".yt");
const numberfb = document.querySelector(".numberfb");
const numbertw = document.querySelector(".numbertw");
const numberig = document.querySelector(".numberig");
const numberyt = document.querySelector(".numberyt");
const dark1 = document.querySelector(".dark1");
const dark2 = document.querySelector(".dark2");
const dark3 = document.querySelector(".dark3");
const dark4 = document.querySelector(".dark4");
const dark5 = document.querySelector(".dark5");
const dark6 = document.querySelector(".dark6");
const dark7 = document.querySelector(".dark7");
const dark8 = document.querySelector(".dark8");
const darkTab1 = document.querySelector(".darktab1");
const darkTab2 = document.querySelector(".darktab2");
const darkTab3 = document.querySelector(".darktab3");
const darkTab4 = document.querySelector(".darktab4");
const darkTab5 = document.querySelector(".darktab5");
const darkTab6 = document.querySelector(".darktab6");
const darkTab7 = document.querySelector(".darktab7");
const darkTab8 = document.querySelector(".darktab8");

slider.addEventListener("click", function () {
  main.classList.toggle("darkBg");
  socialH.classList.toggle("hColor");
  todayH.classList.toggle("hColor");
  fbTop.classList.toggle("darkBgTab");
  igTop.classList.toggle("darkBgTab");
  twTop.classList.toggle("darkBgTab");
  ytTop.classList.toggle("darkBgTab");
  numberfb.classList.toggle("hColor");
  numbertw.classList.toggle("hColor");
  numberig.classList.toggle("hColor");
  numberyt.classList.toggle("hColor");
  dark1.classList.toggle("hColor");
  dark2.classList.toggle("hColor");
  dark3.classList.toggle("hColor");
  dark4.classList.toggle("hColor");
  dark5.classList.toggle("hColor");
  dark6.classList.toggle("hColor");
  dark7.classList.toggle("hColor");
  dark8.classList.toggle("hColor");
  darkTab1.classList.toggle("darkBgTab");
  darkTab2.classList.toggle("darkBgTab");
  darkTab3.classList.toggle("darkBgTab");
  darkTab4.classList.toggle("darkBgTab");
  darkTab5.classList.toggle("darkBgTab");
  darkTab6.classList.toggle("darkBgTab");
  darkTab7.classList.toggle("darkBgTab");
  darkTab8.classList.toggle("darkBgTab");
  fbTop.classList.toggle("info-hover");
  igTop.classList.toggle("info-hover");
  twTop.classList.toggle("info-hover");
  ytTop.classList.toggle("info-hover");
  darkTab1.classList.toggle("info-hover");
  darkTab2.classList.toggle("info-hover");
  darkTab3.classList.toggle("info-hover");
  darkTab4.classList.toggle("info-hover");
  darkTab5.classList.toggle("info-hover");
  darkTab6.classList.toggle("info-hover");
  darkTab7.classList.toggle("info-hover");
  darkTab8.classList.toggle("info-hover");
});
